Repository web-token/jwt-framework, pull requests merged in 2024-04, with the labels that each got.

#550 Add PSR6 alternative to cache JWKSet
  composer.json
  phpstan-baseline.neon
  src/Library/KeyManagement/UrlKeySetFactory.php
  src/Library/composer.json
Labels: enhancement

#554 Remove UTF-8 encoding check in JWEBuilder
  src/Library/Encryption/JWEBuilder.php
Labels: bug

#557 Add new testing options and refactor code for clarity.
  .gitattributes
  .github/workflows/infection.yml
  .github/workflows/integrate.yml
  .gitignore
  castor.php
  ecs.php
  rector.php
  src/Library/Checker/AlgorithmChecker.php
  src/Library/Checker/AudienceChecker.php
  src/Library/Checker/CallableChecker.php
  src/Library/Checker/ClaimChecker.php
  src/Library/Checker/ClaimCheckerManager.php
  src/Library/Checker/ClaimCheckerManagerFactory.php
  src/Library/Checker/ClaimExceptionInterface.php
  src/Library/Checker/ExpirationTimeChecker.php
  src/Library/Checker/HeaderChecker.php
  src/Library/Checker/HeaderCheckerManager.php
  src/Library/Checker/HeaderCheckerManagerFactory.php
  src/Library/Checker/InvalidHeaderException.php
  src/Library/Checker/IsEqualChecker.php
  src/Library/Checker/IssuerChecker.php
  src/Library/Checker/MissingMandatoryClaimException.php
  src/Library/Checker/TokenTypeSupport.php
Labels: CI-CD

#556 Avoid PHP warnings about undefined array keys when sanitizing malformed PEMs
  src/Library/KeyManagement/KeyConverter/KeyConverter.php
  tests/Component/KeyManagement/Keys/ECKeysTest.php
Labels: bug, in progress

#562 Update trigger for gitsplit workflow
  .github/workflows/gitsplit.yml
Labels: bug

#564 Restore repositories to .gitsplit.yml
  .gitsplit.yml
Labels: CI-CD
